DROP TABLE IF EXISTS ITEM_WEAPON_BASE;

CREATE TABLE ITEM_WEAPON_BASE (
	ITEM_ID TEXT NOT NULL,
	NAME_KEY TEXT NOT NULL,
	DESC_KEY TEXT NOT NULL,
	RES_KEY TEXT NOT NULL,
	KNOCK_BACK INTEGER,
	BASE_POWER REAL,
	BASE_AMOUNT INTEGER,
	BASE_SPEED REAL,
	BASE_DURATION REAL,
	BASE_COOLDOWN REAL,
	BASE_PIERCE INTEGER,
	CONSTRAINT ITEM_WEAPON_BASE_PK PRIMARY KEY (ITEM_ID)
);
