DROP TABLE IF EXISTS ITEM_EVOLUTION;

CREATE TABLE ITEM_EVOLUTION (
	ITEM_ID TEXT NOT NULL,
	ITEM1_ID TEXT NOT NULL,
	ITEM1_LEVEL INTEGER NOT NULL,
	ITEM1_CONSUME INTEGER NOT NULL DEFAULT 1,
	ITEM2_ID TEXT NOT NULL,
	ITEM2_LEVEL INTEGER NOT NULL,
	ITEM2_CONSUME INTEGER NOT NULL DEFAULT 0,
	ITEM3_ID TEXT,
	ITEM3_LEVEL INTEGER,
	ITEM3_CONSUME INTEGER,
	CONSTRAINT ITEM_EVOLUTION_PK PRIMARY KEY (ITEM_ID)
);