DROP TABLE IF EXISTS ITEM_EVOLUTION;

CREATE TABLE ITEM_EVOLUTION (
	ITEM_ID TEXT NOT NULL,
	ITEM1_ID TEXT NOT NULL,
	ITEM1_LEVEL INTEGER NOT NULL,
	ITEM1_CONSUME BOOLEAN NOT NULL DEFAULT TRUE,
	ITEM2_ID TEXT NOT NULL,
	ITEM2_LEVEL INTEGER NOT NULL,
	ITEM2_CONSUME BOOLEAN NOT NULL DEFAULT FALSE,
	ITEM3_ID TEXT,
	ITEM3_LEVEL INTEGER,
	ITEM3_CONSUME BOOLEAN,
	CONSTRAINT ITEM_EVOLUTION_PK PRIMARY KEY (ITEM_ID)
);