DROP TABLE IF EXISTS ITEM_ACCESSORY_LEVEL;

CREATE TABLE ITEM_ACCESSORY_LEVEL (
	ITEM_ID TEXT NOT NULL,
	LEVEL INTEGER NOT NULL,
	ADD_POWER REAL,
	ADD_AREA REAL,
	ADD_AMOUNT INTEGER,
	ADD_SPEED REAL,
	ADD_DURATION REAL,
	ADD_COOLDOWN REAL,
	CONSTRAINT ITEM_ACCESSORY_LEVEL_PK PRIMARY KEY (ITEM_ID, LEVEL)
);