DROP TABLE IF EXISTS ITEM_ACCESSORY_BASE;

CREATE TABLE ITEM_ACCESSORY_BASE (
	ITEM_ID TEXT NOT NULL,
	NAME_KEY TEXT NOT NULL,
	DESC_KEY TEXT NOT NULL,
	RES_KEY TEXT NOT NULL,
	CONSTRAINT ITEM_ACCESSORY_BASE_PK PRIMARY KEY (ITEM_ID)
);
