DROP TABLE IF EXISTS MONSTER_ENTITY;

CREATE TABLE MONSTER_ENTITY (
	ENTITY_ID TEXT NOT NULL,
	MONSTER_ID TEXT NOT NULL,
	RES_KEY TEXT NOT NULL,
	HP REAL NOT NULL,
	POWER REAL NOT NULL,
	SPEED REAL NOT NULL,
	CONSTRAINT MONSTER_ENTITY_PK PRIMARY KEY (ENTITY_ID)
);