DROP TABLE IF EXISTS MONSTER_BASE;

CREATE TABLE MONSTER_BASE (
	MONSTER_ID TEXT NOT NULL,
	NAME_KEY TEXT NOT NULL,
	DESC_KEY TEXT NOT NULL,
	RES_KEY TEXT NOT NULL,
	CONSTRAINT MONSTER_BASE_PK PRIMARY KEY (MONSTER_ID)
);