DROP TABLE IF EXISTS STAGE_EVENT;

CREATE TABLE STAGE_EVENT (
	STAGE_ID TEXT NOT NULL,
	NAME_KEY TEXT NOT NULL,
	DESC_KEY TEXT NOT NULL,
	RES_KEY TEXT NOT NULL,
	CONSTRAINT STAGE_EVENT_PK PRIMARY KEY (STAGE_ID)
);