DROP TABLE IF EXISTS STAGE_EVENT;

CREATE TABLE STAGE_EVENT (
	STAGE_ID TEXT NOT NULL,
	ELAPSED_TIME INTEGER NOT NULL,
	EVENT_TYPE INTEGER NOT NULL,
	EVENT_INTERVAL REAL NOT NULL,
	MONSTER_ID TEXT NOT NULL,
	EXP_TIER INTEGER NOT NULL,
	CONSTRAINT STAGE_EVENT_PK PRIMARY KEY (STAGE_ID, ELAPSED_TIME)
);