DROP TABLE IF EXISTS STAGE_WAVE;

CREATE TABLE STAGE_WAVE (
	STAGE_ID TEXT NOT NULL,
	ELAPSED_TIME INTEGER NOT NULL,
	MONSTER_ID TEXT NOT NULL,
	SPAWN_INTERVAL REAL NOT NULL,
	EXP_TIER INTEGER NOT NULL,
	CONSTRAINT STAGE_WAVE_PK PRIMARY KEY (STAGE_ID, ELAPSED_TIME, MONSTER_ID)
);