DROP TABLE IF EXISTS STAGE_BOSS;

CREATE TABLE STAGE_BOSS (
	STAGE_ID TEXT NOT NULL,
	ELAPSED_TIME INTEGER NOT NULL,
	MONSTER_ID TEXT NOT NULL,
	DROP_TYPE INTEGER NOT NULL,
	HP_RATE REAL NOT NULL,
	POWER_RATE REAL NOT NULL,
	SPEED_RATE REAL NOT NULL,
	SCALE_RATE REAL NOT NULL,
	CONSTRAINT STAGE_BOSS_PK PRIMARY KEY (STAGE_ID, ELAPSED_TIME)
);