DROP TABLE IF EXISTS SYSTEM_LOCALIZATION;

CREATE TABLE SYSTEM_LOCALIZATION (
	STRING_KEY TEXT NOT NULL,
	KO_KR TEXT NOT NULL,
	EN_US TEXT NOT NULL,
	CONSTRAINT SYSTEM_LOCALIZATION_PK PRIMARY KEY (STRING_KEY)
);