------------------------------------------------------------
-- VIEW_ITEM_WEAPON_STAT
-- 레벨별 무기 스탯 정보
------------------------------------------------------------

DROP VIEW IF EXISTS VIEW_ITEM_WEAPON_STAT;

CREATE VIEW VIEW_ITEM_WEAPON_STAT AS
SELECT
IB.ITEM_ID,
LEVEL,
IB.BASE_POWER +
(
	SELECT SUM(IFNULL(IL2.ADD_POWER, 0))
	FROM ITEM_WEAPON_LEVEL IL2
	WHERE IB.ITEM_ID = IL2.ITEM_ID
	AND IL2.LEVEL <= IL.LEVEL
) AS POWER,
-- (%) IB.BASE_AREA +
100 + 
(
	SELECT SUM(IFNULL(IL2.ADD_AREA, 0))
	FROM ITEM_WEAPON_LEVEL IL2
	WHERE IB.ITEM_ID = IL2.ITEM_ID
	AND IL2.LEVEL <= IL.LEVEL
) AS AREA,
IB.BASE_AMOUNT +
(
	SELECT SUM(IFNULL(IL2.ADD_AMOUNT, 0))
	FROM ITEM_WEAPON_LEVEL IL2
	WHERE IB.ITEM_ID = IL2.ITEM_ID
	AND IL2.LEVEL <= IL.LEVEL
) AS AMOUNT,
IB.BASE_SPEED +
(
	SELECT SUM(IFNULL(IL2.ADD_SPEED, 0))
	FROM ITEM_WEAPON_LEVEL IL2
	WHERE IB.ITEM_ID = IL2.ITEM_ID
	AND IL2.LEVEL <= IL.LEVEL
) AS SPEED,
IB.BASE_DURATION +
(
	SELECT SUM(IFNULL(IL2.ADD_DURATION, 0))
	FROM ITEM_WEAPON_LEVEL IL2
	WHERE IB.ITEM_ID = IL2.ITEM_ID
	AND IL2.LEVEL <= IL.LEVEL
) AS DURATION,
IB.BASE_COOLDOWN +
(
	SELECT SUM(IFNULL(IL2.ADD_COOLDOWN, 0))
	FROM ITEM_WEAPON_LEVEL IL2
	WHERE IB.ITEM_ID = IL2.ITEM_ID
	AND IL2.LEVEL <= IL.LEVEL
) AS COOLDOWN,
IB.BASE_PIERCE +
(
	SELECT SUM(IFNULL(IL2.ADD_PIERCE, 0))
	FROM ITEM_WEAPON_LEVEL IL2
	WHERE IB.ITEM_ID = IL2.ITEM_ID
	AND IL2.LEVEL <= IL.LEVEL
) AS PIERCE
FROM ITEM_WEAPON_BASE IB
JOIN ITEM_WEAPON_LEVEL IL
ON IB.ITEM_ID = IL.ITEM_ID -- 일반 무기(레벨 테이블에 존재하는 무기)

UNION ALL

SELECT
IB.ITEM_ID,
1 AS LEVEL,
IB.BASE_POWER AS POWER,
100 AS AREA,
IB.BASE_AMOUNT AS AMOUNT,
IB.BASE_SPEED AS SPEED,
IB.BASE_DURATION AS DURATION,
IB.BASE_COOLDOWN AS COOLDOWN,
IB.BASE_PIERCE AS PIERCE
FROM ITEM_WEAPON_BASE IB
WHERE IB.ITEM_ID NOT IN (SELECT DISTINCT ITEM_ID FROM ITEM_WEAPON_LEVEL)

ORDER BY ITEM_ID, LEVEL;